config/routes.rb
Rails.application.routes.draw do

  get 'signup', to: 'users#new', as: 'signup'

  get 'users/new', to: 'users#new', as: 'new_user'

  post 'users', to: 'users#create'

  post 'signup', to: 'users#create'

  get 'users/:id', to: 'users#show', as: 'user'

  get 'users/:id/edit', to: 'users#edit', as: 'edit_user'

  patch 'users/:id', to: 'users#update'

  get 'sessions/new', to: 'sessions#new', as: 'login'

  post 'sessions/new', to: 'sessions#create', as: 'new_session'

  get 'sessions/destroy', to: 'sessions#destroy', as: 'logout'


  get 'courses/index'

  get 'home/index'

  root to: 'home#index'

  get 'yoga', to: 'home#yoga'

  get 'gifs', to: 'home#giphy', as: 'gifs'

  # get 'vine', to: 'home#vine'
  #
  # post 'vine', to: 'home#vineget'

  get 'periscope', to: 'home#periscope', as: 'periscope'

  get 'tweets', to: 'home#tweet', as: 'tweet'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password


  def self.confirm(params)
    user = User.find_by(email: params[:email])

    if user

    user = user.authenticate(password: params[:password])
    puts user
    user

    else
    redirect_to signup_path
    end

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorize, only: [:new]

  def new
    @user = User.new

  end

  def create

  @user =  User.new(sanitized_params(params))

      if @user.save
        puts @user.inspect
        login(@user)
        # render plain: @current_user.inspect
        redirect_to @user

      else
        render plain: @user.inspect
        render 'new'

      end




  end

  def show
    # render plain: current_user

    @user = User.find(params[:id])

  end

  def edit

    @user = User.find(params[:id])



  end

  def update

    @user = User.find(params[:id])

     if @user.update(sanitized_params(params))
       redirect_to @user
     else
       render 'edit'

     end

  end


  private


  def sanitized_params(params)
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user do |user| %>

          <%= user.label :name %>
          <%= user.text_field :name %>

          <%= user.label :email %>
          <%= user.text_field :email %>

          <%= user.label :password %>
          <%= user.password_field :password %>

          <%= user.label 'Confirm Password' %>
          <%= user.password_field :password_confirmation %>


          <% if @user.persisted? %>

          <%= user.submit 'Edit Profile' %>

          <% else %>
          <%= user.submit 'Sign Up' %>


          <% end %>

<% end %>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>


<%= render 'form' %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h2> User Profile</h2>

<p> Name: <%= current_user.name %> </p>
<p> Email: <%= current_user.email %> </p>



<%= link_to 'Edit profile', edit_user_path(current_user) %> <br>

<%= link_to 'Home', root_path %>
<br>
<%= link_to 'Logout', logout_path %>