config/routes.rb
Rails.application.routes.draw do

  get 'signup', to: 'users#new', as: 'signup'

  get 'users/new', to: 'users#new', as: 'new_user'

  post 'users', to: 'users#create'

  post 'signup', to: 'users#create'

  get 'users/:id', to: 'users#show', as: 'user'

  get 'users/:id/edit', to: 'users#edit', as: 'edit_user'

  patch 'users/:id', to: 'users#update'

  get 'sessions/new', to: 'sessions#new', as: 'login'

  post 'sessions/new', to: 'sessions#create', as: 'new_session'

  get 'sessions/destroy', to: 'sessions#destroy', as: 'logout'


  get 'courses/index'

  get 'home/index'

  root to: 'home#index'

  get 'yoga', to: 'home#yoga'

  get 'gifs', to: 'home#giphy', as: 'gifs'

  # get 'vine', to: 'home#vine'
  #
  # post 'vine', to: 'home#vineget'

  get 'periscope', to: 'home#periscope', as: 'periscope'

  get 'tweets', to: 'home#tweet', as: 'tweet'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
require 'httparty'


class HomeController < ApplicationController
  skip_before_action :authorize







  def index


  end



  def giphy

    @gifs = Giphy.for('Dallas Cowboys')['data']

  end
  def vine

    # Note that the parameters below for the vine username and passwords should be replaced with your own credentials. For some reason, using environment variables didn't work for me, so I ended up having to hardcode my credentials.
    # vine = API.new(ENV['VINE_USERNAME]', ENV['VINE_PASSWORD']) #should be uncommented in production with your own credentials in place
    @vines = vine.tagged('dallascowboys')

  end



  def tweet

    # The commented out code is another way to pull tweets that just gives you the json for the tweet. For my production app, I opted for a different method that involves just using Twitter's embedded timelines feature.
    # client = Twitter::REST::Client.new do |config|
    # config.consumer_key        = ENV['TWITTER_KEY']
    # config.consumer_secret     = ENV['TWITTER_SECRET']
    # config.access_token        = ENV['TWITTER_TOKEN']
    # config.access_token_secret = ENV['TWITTER_TOKEN_SECRET']
  # end





  end

  # Both the periscope and tweet feeds use the same Twitter embedded timeline code from its API. The only difference is that when you go to set up your timeline on the dev website you add an 'filter:periscope at the end of your search query'

  def periscope

  render 'embedded_periscope'

  end

  def tweet

  render 'embedded_twitter'

  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/embedded_periscope.html.erb
<h2> Dallas Cowboys Periscope </h2>
<div style="text-align: center">
<a class="twitter-timeline"  href="https://twitter.com/search?q=Dallas%20Cowboys%20filter%3Aperiscpoe" data-widget-id="774762989689851906" data-chrome="nofooter noborders noheader" data-width="600"></a>
</div>

app/views/home/embedded_twitter.html.erb
<h2> 49ers tweets </h2>

<div style="text-align: center">

<a class="twitter-timeline" data-dnt="true" href="https://twitter.com/search?q=49ers" data-widget-id="776445623851560961" data-chrome="nofooter noborders noheader" ></a>


</div>

app/views/home/get_tweets.html.erb
<h2>
    Tweets YALL
</h2>

<% @stuff.each do |tweet| %>

<p><%= tweet %>
</p>

<% end %>

app/views/home/giphy.html.erb
<h2> GIFS homie </h2>

<%  @gifs.each do |gif| %>

<img src=<%= gif['images']['fixed_height']['url'] %>>


<% end %>

app/views/home/index.html.erb
<h1>SportVine</h1>

<p> <b>NOTE: </b>
The proper stylized representation of this underlying code can be found here <%=link_to 'Sportline app\'s MediaVine', 'http://www.sportlineapp.com/mediavine' %>
</p>


<%= link_to 'Dallas Cowboys GIFs', gifs_path %><br>
<%= link_to '49ers Tweets', tweet_path %><br>
<%= link_to 'Periscope broadcasts for Dallas Cowboys', periscope_path %>

app/views/home/vine.html.erb
<% @vines.first(3).each do |vine| %>

<%= raw vine.embed_tag(:postcard) %>
<br>
<br>


<% end %>